import '@/styles/globals.css';
import dynamic from 'next/dynamic';
import type { Metadata } from 'next';
import { IRootLayout } from '@/types';
import { Inter } from 'next/font/google';
import { StorageContextProvider } from '@/context/storage';
import { NextAuthProvider } from '@/lib/providers/next-auth';
import { NavbarProgressProvider } from '@/lib/providers/loader';
import { getLang } from '@/lib/_actions/helpers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = async ({ children }: IRootLayout) => {
  const GearProvider = dynamic(() => import('@/lib/providers/gear'), {
    ssr: false,
  });

  const lang = await getLang();

  return (
    <html lang={lang}>
      <body className={`${inter.className} bg-neutral-900 text-gray-300`}>
        <NextAuthProvider>
          <GearProvider>
            <StorageContextProvider>{children}</StorageContextProvider>
          </GearProvider>
        </NextAuthProvider>
        <NavbarProgressProvider />
      </body>
    </html>
  );
};

export default RootLayout;
