import {
  EnkryptSVG,
  NovaSVG,
  PolkadotSVG,
  SubwalletPNG,
  TalismanPNG,
} from '@/assets/static';
import { proxy } from 'valtio';
import { IArticle, IBlog, IPage, ISocial } from '@/types';
import {
  CircleDollarSign,
  FileText,
  Github,
  Group,
  Radar,
  Rss,
  Settings,
  Settings2,
} from 'lucide-react';
import { emptyParagraph } from '@/components/editor/lib/constants';

export const providers = [
  { name: 'github', proxy: '1c4v90ving1t43du3924DMehKqsPt4tuXHx' },
  { name: 'google', proxy: 'h380wqjs90cxdsfi92h8rdxnOHEXEDj3iewd' },
];

export const supportedWallets = [
  {
    name: 'Talisman',
    value: 'talisman',
    props: {
      className: 'p-1',
      isSupported: true,
      logo: TalismanPNG,
    },
  },
  {
    name: 'Enkrypt',
    value: 'enkrypt',
    props: {
      className: 'p-3',
      isSupported: true,
      logo: EnkryptSVG,
    },
  },
  {
    name: 'Subwallet',
    value: 'subwallet-js',
    props: {
      className: '',
      isSupported: true,
      logo: SubwalletPNG,
    },
  },
  {
    name: 'Polkadot.JS',
    value: 'polkadot-js',
    props: {
      className: 'p-3',
      isSupported: true,
      logo: PolkadotSVG,
    },
  },
  {
    name: 'Nova Wallet',
    value: 'nova',
    props: {
      className: 'p-2.5',
      isSupported: true,
      logo: NovaSVG,
    },
  },
];

export const socials: ISocial[] = [
  {
    name: 'Facebook',
    domain: 'https://www.facebook.com',
    icon: `/socials/facebook.svg`,
    handler: '',
    hide: false,
    showOnPost: false,
  },
  {
    name: 'Instagram',
    domain: 'https://www.instagram.com',
    icon: `/socials/instagram.svg`,
    handler: '',
    hide: false,
    showOnPost: false,
  },
  {
    name: 'X',
    domain: 'https://www.x.com',
    icon: `/socials/x.svg`,
    handler: '',
    hide: false,
    showOnPost: false,
  },
  {
    name: 'Discord',
    domain: 'https://discord.com',
    icon: `/socials/discord.svg`,
    handler: '',
    hide: false,
    showOnPost: false,
  },
  {
    name: 'LinkedIn',
    domain: 'https://www.linkedin.com/in/',
    icon: `/socials/linkedin.svg`,
    handler: '',
    hide: false,
    showOnPost: false,
  },
  {
    name: 'Reddit',
    domain: 'https://www.reddit.com/user/',
    icon: `/socials/reddit.svg`,
    handler: '',
    hide: false,
    showOnPost: false,
  },
  {
    name: 'Hackernoon',
    domain: 'https://hackernoon.com/u/',
    icon: `/socials/hackernoon.svg`,
    handler: '',
    hide: false,
    showOnPost: false,
  },
  {
    name: 'Hashnode',
    domain: 'https://hashnode.com/@',
    icon: `/socials/hashnode.svg`,
    handler: '',
    hide: false,
    showOnPost: false,
  },
  {
    name: 'StackOverflow',
    domain: 'https://stackoverflow.com/users/',
    icon: `/socials/stackoverflow.svg`,
    handler: '',
    hide: false,
    showOnPost: false,
  },
  {
    name: 'GitLab',
    domain: 'https://gitlab.com/',
    icon: `/socials/gitlab.svg`,
    handler: '',
    hide: false,
    showOnPost: false,
  },
  {
    name: 'GitBucket',
    domain: 'https://gitbucket.com/',
    icon: `/socials/gitbucket.svg`,
    handler: '',
    hide: false,
    showOnPost: false,
  },
  {
    name: 'Y-Combinator',
    domain: 'https://news.ycombinator.com/user?id=',
    icon: `/socials/y-combinator.svg`,
    handler: '',
    hide: false,
    showOnPost: false,
  },
  {
    name: 'YouTube',
    domain: 'https://www.youtube.com/user/',
    icon: `/socials/youtube.svg`,
    handler: '',
    hide: false,
    showOnPost: false,
  },
];

export const social: ISocial = {
  name: '',
  domain: '',
  icon: '',
  handler: '',
  hide: false,
  showOnPost: false,
};

export const BlogInit: IBlog = {
  id: '0x',
  owner: '0x',
  createdBy: '0x',
  title: '',
  subdomain: '',
  description: '',
  category: '',
  keywords: '',
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
  customDomain: '',
  visibility: 'Public',
  status: 'Active',
  niche: '',
  socials: '',
  sponsors: '',
  favicon: '',
};

export const USER_PROGRAM_ID: `0x${string}` = `0xb894ae37a69382d4ecbb10b0fd7a36a9660a9886241b9d1c57716210e09fd3a2`;
export const ARTICLE_PROGRAM_ID: `0x${string}` = `0xa1272eecbaee52d04454d051fc3f573d78a41b430d5bfeab8adb000de525d9a3`;
export const BLOG_PROGRAM_ID: `0x${string}` = `0xd62ce4aa138fb1f7368d31a0b6c91af78dbf23b21e8bc80edd2411c20e290f3a`;
export const PAGE_PROGRAM_ID: `0x${string}` = `0x1a762a9676a68e44b92918b539f87208880940c1801698597eb8a91287fe5ba2`;
export const ACCOUNT_ID: `0x${string}` = `0x09dd9fca8bbc9651a71f0583a42d58c49197eb78c3ddd1e634df289d2a5d52b9`;

export const vcPayload = {
  sub: 'did:web:deconnect.vercel.app',
  nbf: 1562950282,
  vc: {
    '@context': ['https://www.w3.org/2018/credentials/v1'],
    type: ['VerifiableCredential'],
    credentialSubject: {
      degree: {
        type: 'BachelorDegree',
        name: 'Baccalauréat en musiques numériques',
      },
    },
  },
};

export const localeLanguage = [
  { code: 'en', name: 'English' },
  { code: 'zh', name: 'Mandarin Chinese' },
  { code: 'es', name: 'Spanish' },
  { code: 'hi', name: 'Hindi' },
  { code: 'ar', name: 'Arabic' },
  { code: 'bn', name: 'Bengali' },
  { code: 'pt', name: 'Portuguese' },
  { code: 'ru', name: 'Russian' },
  { code: 'ja', name: 'Japanese' },
  { code: 'pa', name: 'Western Punjabi' },
  { code: 'mr', name: 'Marathi' },
  { code: 'te', name: 'Telugu' },
  { code: 'zh-wuu', name: 'Wu Chinese' },
  { code: 'tr', name: 'Turkish' },
  { code: 'ko', name: 'Korean' },
  { code: 'fr', name: 'French' },
  { code: 'de', name: 'German' },
  { code: 'vi', name: 'Vietnamese' },
  { code: 'ta', name: 'Tamil' },
  { code: 'ur', name: 'Urdu' },
  { code: 'jv', name: 'Javanese' },
  { code: 'it', name: 'Italian' },
  { code: 'ar-EG', name: 'Egyptian Arabic' },
  { code: 'gu', name: 'Gujarati' },
  { code: 'fa', name: 'Iranian Persian' },
];

export const settingsListsItem = [
  'General',
  // 'Profile',
  'Support',
  'Connect',
  'Advance',
  'Plan',
];

export const GlobalState = proxy({
  dashboardSettingNavState: true,
  dashboardSettingSupportState: true,
  subNavbarState: true,
});

export const pageListsItem = [
  { name: 'Basic', icon: <Github size={20} strokeWidth={2.25} /> },
  { name: 'Social Media', icon: <Group size={20} strokeWidth={2.25} /> },
  {
    name: 'Monetization',
    icon: <CircleDollarSign size={20} strokeWidth={2.25} />,
  },
  { name: 'Readme', icon: <Rss size={20} strokeWidth={2.25} /> },
  // { name: 'Advanced Settings', icon: <Settings2 size={20} strokeWidth={2.25} /> },
];

export const articleListsItem = [
  { name: 'Content', icon: <Github size={20} strokeWidth={2.25} /> },
  { name: 'Settings', icon: <Settings size={20} strokeWidth={2.25} /> },
];

export const pageInit: IPage = {
  id: '0x',
  owner: '0x',
  createdBy: '0x',
  name: '',
  username: '',
  description: '',
  pageType: '',
  category: '',
  focusedTags: [],
  tags: [],
  profile: '',
  cover: '',
  members: [],
  articles: [],
  posts: [],
  events: [],
  socials: [],
  isPremium: false,
  compareEntryAmount: '',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  status: 'Active',
  visibility: 'Public',
  admins: [],
  sponsors: [],
  favicon: '',
  title: '',
  readme: 'wqwqw',
  entryAmount: '',
  contactEmail: '',
  website: 'qqw',
  pageRules: 'wqwqw',
};

export const mimeTypes = [
  'deb',
  'rpm',
  'app',
  'ipa',
  'dmg',
  'msi',
  'rs',
  'c',
  'cpp',
  'cs',
  'java',
  'py',
  'js',
  'rb',
  'php',
  'swift',
  'go',
  'rust',
  'ts',
  'html',
  'css',
  'json',
  'xml',
  'sh',
  'pl',
  'kt',
  'lua',
  'objc',
  'ps1',
  'sql',
  'vb',
  'cr',
  'ex',
  'f90',
  'ml',
  'groovy',
  'puppet',
  'matlab',
  'r',
  'scala',
  'haskell',
  'dart',
  'erlang',
  'julia',
  'perl',
  'kotlin',
  'lisp',
  'ada',
  'pro',
  'cob',
  'scm',
  'e',
  'awk',
  'ahk',
  'purs',
  'elm',
  're',
  'crystal',
  'groovy',
  'julia',
  'mips',
  'ps',
  'rkt',
  'lua',
  'vb',
  'rexx',
  'hack',
  'abap',
  'elixir',
  'dylan',
  'factor',
  'forth',
  'io',
  'j',
  'nim',
  'oz',
  'pli',
  'sather',
  'vhdl',
  'x10',
  'bal',
  'bef',
  'chpl',
  'd',
  'hx',
  'ttf',
  'otf',
  'woff',
  'woff2',
  'eot',
  'svg',
  'pfa',
  'pfb',
  'ps',
  'zip',
  'rar',
  '7z',
  'tar',
  'gz',
  'bz2',
  'xz',
  'lz',
  'Z',
  'lha',
  'lzh',
  'cab',
  'iso',
  'gltf',
  'glb',
];

export const assignedMimeTypes: { [key: string]: string } = {
  zip: 'application/zip',
  rar: 'application/x-rar-compressed',
  '7z': 'application/x-7z-compressed',
  tar: 'application/x-tar',
  gz: 'application/gzip',
  gltf: 'model/gltf+json',
  glb: 'model/gltf-binary',
  bz2: 'application/x-bzip2',
  xz: 'application/x-xz',
  lz: 'application/x-lzip',
  Z: 'application/x-compress',
  lha: 'application/x-lha',
  lzh: 'application/x-lha',
  cab: 'application/vnd.ms-cab-compressed',
  iso: 'application/x-iso9660-image',
  ttf: 'application/font-sfnt',
  otf: 'application/font-sfnt',
  woff: 'font/woff',
  woff2: 'font/woff2',
  eot: 'application/vnd.ms-fontobject',
  svg: 'font/svg',
  pfa: 'application/x-font-type1',
  pfb: 'application/x-font-type1',
  ps: 'application/postscript',
  deb: 'application/vnd.debian.binary-package',
  rpm: 'application/x-rpm',
  app: 'application/octet-stream',
  ipa: 'application/octet-stream',
  dmg: 'application/x-apple-diskimage',
  msi: 'application/x-msdownload',
  xls: 'application/vnd.ms-excel',
  xlsx: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  doc: 'application/msword',
  docx: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document ',
  ppt: 'application/vnd.ms-powerpoint',
  pptx: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  pdf: 'application/pdf',
  rs: 'text/x-rustsrc',
  c: 'text/x-csrc',
  cpp: 'text/x-c++src',
  cs: 'text/x-csharp',
  java: 'text/x-java-source',
  py: 'text/x-python',
  js: 'text/javascript',
  rb: 'text/x-ruby',
  php: 'text/x-php',
  swift: 'text/x-swift',
  go: 'text/x-go',
  rust: 'text/x-rustsrc',
  ts: 'text/typescript',
  html: 'text/html',
  css: 'text/css',
  json: 'text/json',
  xml: 'text/xml',
  sh: 'text/x-sh',
  pl: 'text/x-perl',
  kt: 'text/x-kotlin',
  lua: 'text/x-lua',
  objc: 'text/x-objectivec',
  ps1: 'text/x-powershell',
  sql: 'text/sql',
  cr: 'text/x-crystal',
  ex: 'text/x-elixir',
  f90: 'text/x-fortran',
  ml: 'text/x-ocaml',
  groovy: 'text/x-groovy',
  puppet: 'text/x-puppet',
  matlab: 'text/matlab',
  r: 'text/x-rsrc',
  scala: 'text/x-scala',
  haskell: 'text/x-haskell',
  dart: 'text/dart',
  erlang: 'text/x-erlang',
  julia: 'text/julia',
  perl: 'text/perl',
  kotlin: 'text/x-kotlin',
  lisp: 'text/x-lisp',
  ada: 'text/x-ada',
  pro: 'text/x-prolog',
  cob: 'text/x-cobol',
  scm: 'text/x-scheme',
  e: 'text/x-eiffel',
  awk: 'text/x-awk',
  ahk: 'text/x-autohotkey',
  purs: 'text/x-purescript',
  elm: 'text/x-elm',
  re: 'text/x-reasonml',
  crystal: 'text/x-crystal',
  mips: 'text/x-mips',
  rkt: 'text/x-racket',
  vb: 'text/x-vb',
  rexx: 'text/rexx',
  hack: 'text/x-hack',
  abap: 'text/plain',
  elixir: 'text/x-elixir',
  dylan: 'text/x-dylan',
  factor: 'text/x-factor',
  forth: 'text/x-forth',
  io: 'text/x-io',
  j: 'text/plain',
  nim: 'text/x-nim',
  oz: 'text/x-oz',
  pli: 'text/x-pli',
  sather: 'text/plain',
  vhdl: 'text/x-vhdl',
  x10: 'text/x-x10',
  bal: 'text/plain',
  bef: 'text/plain',
  chpl: 'text/x-chapel',
  d: 'text/x-d',
  hx: 'text/plain',
};

export const articleInit: IArticle = {
  id: '0x',
  title: '',
  owner: '0x',
  createdBy: '0x',
  slug: '',
  tags: [],
  cover: '',
  category: '',
  subCategory: '',
  caption: '',
  audioUrl: '',
  publishedOn: new Date().toISOString(),
  keywords: [],
  isTransferred: false,
  status: 'Active',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  description: '',
  lang: '',
  license: '',
  licenseContent: '',
  latestPublishedDate: new Date().toISOString(),
  otherPublications: [],
  hideComments: false,
  contributors: [],
  visibility: 'Public',
  content: emptyParagraph as unknown as string,
  isChatEnabled: false,
  seoTitle: '',
};
